name: Bump version

on:
  push:
    branches:
    - main

jobs:
  bump:
    runs-on: ubuntu-latest
    env:
      working-directory: ./lib
    steps:
    - name: Conventional Commits Version Bump
      uses: soamee/gh-action-conventional-commits@v8.0.3
